use super::instruction::{Arg::*, Instruction, Instruction::*};

pub const OP_TABLE: [Instruction; 256] = [
    // 0x
    NOP,                  // x0
    LD(R16_BC, IMM_16),   // x1*
    LD(M_BC, R8_A),       // x2
    INC(R16_BC),          // x3
    INC(R8_B),            // x4
    DEC(R8_B),            // x5
    LD(R8_B, IMM_8),      // x6
    RLCA,                 // x7
    LD(M_IMM_16, R16_SP), // x8
    ADD(R16_HL, R16_BC),  // x9
    LD(R8_A, M_BC),       // xA
    DEC(R16_BC),          // xB
    INC(R8_C),            // xC
    DEC(R8_C),            // xD
    LD(R8_C, IMM_8),      // xE
    RRCA,                 // xF
    // 1x
    STOP(IMM_8),         // x0
    LD(R16_DE, IMM_16),  // x1
    LD(M_DE, R8_A),      // x2
    INC(R16_DE),         // x3
    INC(R8_D),           // x4
    DEC(R8_D),           // x5
    LD(R8_D, IMM_8),     // x6
    RLA,                 // x7
    JR(NO_ARG, IMM_i8),  // x8
    ADD(R16_HL, R16_DE), // x9
    LD(R8_A, M_DE),      // xA
    DEC(R16_DE),         // xB
    INC(R8_E),           // xC
    DEC(R8_E),           // xD
    LD(R8_E, IMM_8),     // xE
    RRA,                 // xF
    // 2x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // 3x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // 4x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // 5x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // 6x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // 7x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // 8x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // 9x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // Ax
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // Bx
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // Cx
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // Dx
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // Ex
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // Fx
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
];

pub const PREFIX_TABLE: [Instruction; 256] = [
    // 0x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // 1x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // 2x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // 3x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // 4x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // 5x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // 6x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // 7x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // 8x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // 9x
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // Ax
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // Bx
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // Cx
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // Dx
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // Ex
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
    // Fx
    NOP, // x0
    NOP, // x1
    NOP, // x2
    NOP, // x3
    NOP, // x4
    NOP, // x5
    NOP, // x6
    NOP, // x7
    NOP, // x8
    NOP, // x9
    NOP, // xA
    NOP, // xB
    NOP, // xC
    NOP, // xD
    NOP, // xE
    NOP, // xF
];
