use crate::gb::cpu::instructions::Instruction::{self, *};

pub const OPTABLE: [Instruction; 0x100] = [
    NOP,         // $00
    LD_BC_n16,   // $01
    LD_mBC_A,    // $02
    INC_BC,      // $03
    INC_B,       // $04
    DEC_B,       // $05
    LD_B_n8,     // $06
    RLCA,        // $07
    LD_ma16_SP,  // $08
    ADD_HL_BC,   // $09
    LD_A_mBC,    // $0A
    DEC_BC,      // $0B
    INC_C,       // $0C
    DEC_C,       // $0D
    LD_C_n8,     // $0E
    RRCA,        // $0F
    STOP_n8,     // $10
    LD_DE_n16,   // $11
    LD_mDE_A,    // $12
    INC_DE,      // $13
    INC_D,       // $14
    DEC_D,       // $15
    LD_D_n8,     // $16
    RLA,         // $17
    JR_e8,       // $18
    ADD_HL_DE,   // $19
    LD_A_mDE,    // $1A
    DEC_DE,      // $1B
    INC_E,       // $1C
    DEC_E,       // $1D
    LD_E_n8,     // $1E
    RRA,         // $1F
    JR_NZ_e8,    // $20
    LD_HL_n16,   // $21
    LD_mHLi_A,   // $22
    INC_HL,      // $23
    INC_H,       // $24
    DEC_H,       // $25
    LD_H_n8,     // $26
    DAA,         // $27
    JR_Z_e8,     // $28
    ADD_HL_HL,   // $29
    LD_A_mHLi,   // $2A
    DEC_HL,      // $2B
    INC_L,       // $2C
    DEC_L,       // $2D
    LD_L_n8,     // $2E
    CPL,         // $2F
    JR_NC_e8,    // $30
    LD_SP_n16,   // $31
    LD_mHLd_A,   // $32
    INC_SP,      // $33
    INC_mHL,     // $34
    DEC_mHL,     // $35
    LD_mHL_n8,   // $36
    SCF,         // $37
    JR_C_e8,     // $38
    ADD_HL_SP,   // $39
    LD_A_mHLd,   // $3A
    DEC_SP,      // $3B
    INC_A,       // $3C
    DEC_A,       // $3D
    LD_A_n8,     // $3E
    CCF,         // $3F
    LD_B_B,      // $40
    LD_B_C,      // $41
    LD_B_D,      // $42
    LD_B_E,      // $43
    LD_B_H,      // $44
    LD_B_L,      // $45
    LD_B_mHL,    // $46
    LD_B_A,      // $47
    LD_C_B,      // $48
    LD_C_C,      // $49
    LD_C_D,      // $4A
    LD_C_E,      // $4B
    LD_C_H,      // $4C
    LD_C_L,      // $4D
    LD_C_mHL,    // $4E
    LD_C_A,      // $4F
    LD_D_B,      // $50
    LD_D_C,      // $51
    LD_D_D,      // $52
    LD_D_E,      // $53
    LD_D_H,      // $54
    LD_D_L,      // $55
    LD_D_mHL,    // $56
    LD_D_A,      // $57
    LD_E_B,      // $58
    LD_E_C,      // $59
    LD_E_D,      // $5A
    LD_E_E,      // $5B
    LD_E_H,      // $5C
    LD_E_L,      // $5D
    LD_E_mHL,    // $5E
    LD_E_A,      // $5F
    LD_H_B,      // $60
    LD_H_C,      // $61
    LD_H_D,      // $62
    LD_H_E,      // $63
    LD_H_H,      // $64
    LD_H_L,      // $65
    LD_H_mHL,    // $66
    LD_H_A,      // $67
    LD_L_B,      // $68
    LD_L_C,      // $69
    LD_L_D,      // $6A
    LD_L_E,      // $6B
    LD_L_H,      // $6C
    LD_L_L,      // $6D
    LD_L_mHL,    // $6E
    LD_L_A,      // $6F
    LD_mHL_B,    // $70
    LD_mHL_C,    // $71
    LD_mHL_D,    // $72
    LD_mHL_E,    // $73
    LD_mHL_H,    // $74
    LD_mHL_L,    // $75
    HALT,        // $76
    LD_mHL_A,    // $77
    LD_A_B,      // $78
    LD_A_C,      // $79
    LD_A_D,      // $7A
    LD_A_E,      // $7B
    LD_A_H,      // $7C
    LD_A_L,      // $7D
    LD_A_mHL,    // $7E
    LD_A_A,      // $7F
    ADD_A_B,     // $80
    ADD_A_C,     // $81
    ADD_A_D,     // $82
    ADD_A_E,     // $83
    ADD_A_H,     // $84
    ADD_A_L,     // $85
    ADD_A_mHL,   // $86
    ADD_A_A,     // $87
    ADC_A_B,     // $88
    ADC_A_C,     // $89
    ADC_A_D,     // $8A
    ADC_A_E,     // $8B
    ADC_A_H,     // $8C
    ADC_A_L,     // $8D
    ADC_A_mHL,   // $8E
    ADC_A_A,     // $8F
    SUB_A_B,     // $90
    SUB_A_C,     // $91
    SUB_A_D,     // $92
    SUB_A_E,     // $93
    SUB_A_H,     // $94
    SUB_A_L,     // $95
    SUB_A_mHL,   // $96
    SUB_A_A,     // $97
    SBC_A_B,     // $98
    SBC_A_C,     // $99
    SBC_A_D,     // $9A
    SBC_A_E,     // $9B
    SBC_A_H,     // $9C
    SBC_A_L,     // $9D
    SBC_A_mHL,   // $9E
    SBC_A_A,     // $9F
    AND_A_B,     // $A0
    AND_A_C,     // $A1
    AND_A_D,     // $A2
    AND_A_E,     // $A3
    AND_A_H,     // $A4
    AND_A_L,     // $A5
    AND_A_mHL,   // $A6
    AND_A_A,     // $A7
    XOR_A_B,     // $A8
    XOR_A_C,     // $A9
    XOR_A_D,     // $AA
    XOR_A_E,     // $AB
    XOR_A_H,     // $AC
    XOR_A_L,     // $AD
    XOR_A_mHL,   // $AE
    XOR_A_A,     // $AF
    OR_A_B,      // $B0
    OR_A_C,      // $B1
    OR_A_D,      // $B2
    OR_A_E,      // $B3
    OR_A_H,      // $B4
    OR_A_L,      // $B5
    OR_A_mHL,    // $B6
    OR_A_A,      // $B7
    CP_A_B,      // $B8
    CP_A_C,      // $B9
    CP_A_D,      // $BA
    CP_A_E,      // $BB
    CP_A_H,      // $BC
    CP_A_L,      // $BD
    CP_A_mHL,    // $BE
    CP_A_A,      // $BF
    RET_NZ,      // $C0
    POP_BC,      // $C1
    JP_NZ_a16,   // $C2
    JP_a16,      // $C3
    CALL_NZ_a16, // $C4
    PUSH_BC,     // $C5
    ADD_A_n8,    // $C6
    RST_v00,     // $C7
    RET_Z,       // $C8
    RET,         // $C9
    JP_Z_a16,    // $CA
    PREFIX,      // $CB
    CALL_Z_a16,  // $CC
    CALL_a16,    // $CD
    ADC_A_n8,    // $CE
    RST_v08,     // $CF
    RET_NC,      // $D0
    POP_DE,      // $D1
    JP_NC_a16,   // $D2
    INVALID,     // $D3
    CALL_NC_a16, // $D4
    PUSH_DE,     // $D5
    SUB_A_n8,    // $D6
    RST_v10,     // $D7
    RET_C,       // $D8
    RETI,        // $D9
    JP_C_a16,    // $DA
    INVALID,     // $DB
    CALL_C_a16,  // $DC
    INVALID,     // $DD
    SBC_A_n8,    // $DE
    RST_v18,     // $DF
    LDH_ma8_A,   // $E0
    POP_HL,      // $E1
    LDH_mC_A,    // $E2
    INVALID,     // $E3
    INVALID,     // $E4
    PUSH_HL,     // $E5
    AND_A_n8,    // $E6
    RST_v20,     // $E7
    ADD_SP_e8,   // $E8
    JP_HL,       // $E9
    LD_ma16_A,   // $EA
    INVALID,     // $EB
    INVALID,     // $EC
    INVALID,     // $ED
    XOR_A_n8,    // $EE
    RST_v28,     // $EF
    LDH_A_ma8,   // $F0
    POP_AF,      // $F1
    LDH_A_mC,    // $F2
    DI,          // $F3
    INVALID,     // $F4
    PUSH_AF,     // $F5
    OR_A_n8,     // $F6
    RST_v30,     // $F7
    LD_HL_SPe8,  // $F8
    LD_SP_HL,    // $F9
    LD_A_ma16,   // $FA
    EI,          // $FB
    INVALID,     // $FC
    INVALID,     // $FD
    CP_A_n8,     // $FE
    RST_v38,     // $FF
];

pub const PREFIX_OPTABLE: [Instruction; 0x100] = [
    RLC_B,     // $00
    RLC_C,     // $01
    RLC_D,     // $02
    RLC_E,     // $03
    RLC_H,     // $04
    RLC_L,     // $05
    RLC_mHL,   // $06
    RLC_A,     // $07
    RRC_B,     // $08
    RRC_C,     // $09
    RRC_D,     // $0A
    RRC_E,     // $0B
    RRC_H,     // $0C
    RRC_L,     // $0D
    RRC_mHL,   // $0E
    RRC_A,     // $0F
    RL_B,      // $10
    RL_C,      // $11
    RL_D,      // $12
    RL_E,      // $13
    RL_H,      // $14
    RL_L,      // $15
    RL_mHL,    // $16
    RL_A,      // $17
    RR_B,      // $18
    RR_C,      // $19
    RR_D,      // $1A
    RR_E,      // $1B
    RR_H,      // $1C
    RR_L,      // $1D
    RR_mHL,    // $1E
    RR_A,      // $1F
    SLA_B,     // $20
    SLA_C,     // $21
    SLA_D,     // $22
    SLA_E,     // $23
    SLA_H,     // $24
    SLA_L,     // $25
    SLA_mHL,   // $26
    SLA_A,     // $27
    SRA_B,     // $28
    SRA_C,     // $29
    SRA_D,     // $2A
    SRA_E,     // $2B
    SRA_H,     // $2C
    SRA_L,     // $2D
    SRA_mHL,   // $2E
    SRA_A,     // $2F
    SWAP_B,    // $30
    SWAP_C,    // $31
    SWAP_D,    // $32
    SWAP_E,    // $33
    SWAP_H,    // $34
    SWAP_L,    // $35
    SWAP_mHL,  // $36
    SWAP_A,    // $37
    SRL_B,     // $38
    SRL_C,     // $39
    SRL_D,     // $3A
    SRL_E,     // $3B
    SRL_H,     // $3C
    SRL_L,     // $3D
    SRL_mHL,   // $3E
    SRL_A,     // $3F
    BIT_0_B,   // $40
    BIT_0_C,   // $41
    BIT_0_D,   // $42
    BIT_0_E,   // $43
    BIT_0_H,   // $44
    BIT_0_L,   // $45
    BIT_0_mHL, // $46
    BIT_0_A,   // $47
    BIT_1_B,   // $48
    BIT_1_C,   // $49
    BIT_1_D,   // $4A
    BIT_1_E,   // $4B
    BIT_1_H,   // $4C
    BIT_1_L,   // $4D
    BIT_1_mHL, // $4E
    BIT_1_A,   // $4F
    BIT_2_B,   // $50
    BIT_2_C,   // $51
    BIT_2_D,   // $52
    BIT_2_E,   // $53
    BIT_2_H,   // $54
    BIT_2_L,   // $55
    BIT_2_mHL, // $56
    BIT_2_A,   // $57
    BIT_3_B,   // $58
    BIT_3_C,   // $59
    BIT_3_D,   // $5A
    BIT_3_E,   // $5B
    BIT_3_H,   // $5C
    BIT_3_L,   // $5D
    BIT_3_mHL, // $5E
    BIT_3_A,   // $5F
    BIT_4_B,   // $60
    BIT_4_C,   // $61
    BIT_4_D,   // $62
    BIT_4_E,   // $63
    BIT_4_H,   // $64
    BIT_4_L,   // $65
    BIT_4_mHL, // $66
    BIT_4_A,   // $67
    BIT_5_B,   // $68
    BIT_5_C,   // $69
    BIT_5_D,   // $6A
    BIT_5_E,   // $6B
    BIT_5_H,   // $6C
    BIT_5_L,   // $6D
    BIT_5_mHL, // $6E
    BIT_5_A,   // $6F
    BIT_6_B,   // $70
    BIT_6_C,   // $71
    BIT_6_D,   // $72
    BIT_6_E,   // $73
    BIT_6_H,   // $74
    BIT_6_L,   // $75
    BIT_6_mHL, // $76
    BIT_6_A,   // $77
    BIT_7_B,   // $78
    BIT_7_C,   // $79
    BIT_7_D,   // $7A
    BIT_7_E,   // $7B
    BIT_7_H,   // $7C
    BIT_7_L,   // $7D
    BIT_7_mHL, // $7E
    BIT_7_A,   // $7F
    RES_0_B,   // $80
    RES_0_C,   // $81
    RES_0_D,   // $82
    RES_0_E,   // $83
    RES_0_H,   // $84
    RES_0_L,   // $85
    RES_0_mHL, // $86
    RES_0_A,   // $87
    RES_1_B,   // $88
    RES_1_C,   // $89
    RES_1_D,   // $8A
    RES_1_E,   // $8B
    RES_1_H,   // $8C
    RES_1_L,   // $8D
    RES_1_mHL, // $8E
    RES_1_A,   // $8F
    RES_2_B,   // $90
    RES_2_C,   // $91
    RES_2_D,   // $92
    RES_2_E,   // $93
    RES_2_H,   // $94
    RES_2_L,   // $95
    RES_2_mHL, // $96
    RES_2_A,   // $97
    RES_3_B,   // $98
    RES_3_C,   // $99
    RES_3_D,   // $9A
    RES_3_E,   // $9B
    RES_3_H,   // $9C
    RES_3_L,   // $9D
    RES_3_mHL, // $9E
    RES_3_A,   // $9F
    RES_4_B,   // $A0
    RES_4_C,   // $A1
    RES_4_D,   // $A2
    RES_4_E,   // $A3
    RES_4_H,   // $A4
    RES_4_L,   // $A5
    RES_4_mHL, // $A6
    RES_4_A,   // $A7
    RES_5_B,   // $A8
    RES_5_C,   // $A9
    RES_5_D,   // $AA
    RES_5_E,   // $AB
    RES_5_H,   // $AC
    RES_5_L,   // $AD
    RES_5_mHL, // $AE
    RES_5_A,   // $AF
    RES_6_B,   // $B0
    RES_6_C,   // $B1
    RES_6_D,   // $B2
    RES_6_E,   // $B3
    RES_6_H,   // $B4
    RES_6_L,   // $B5
    RES_6_mHL, // $B6
    RES_6_A,   // $B7
    RES_7_B,   // $B8
    RES_7_C,   // $B9
    RES_7_D,   // $BA
    RES_7_E,   // $BB
    RES_7_H,   // $BC
    RES_7_L,   // $BD
    RES_7_mHL, // $BE
    RES_7_A,   // $BF
    SET_0_B,   // $C0
    SET_0_C,   // $C1
    SET_0_D,   // $C2
    SET_0_E,   // $C3
    SET_0_H,   // $C4
    SET_0_L,   // $C5
    SET_0_mHL, // $C6
    SET_0_A,   // $C7
    SET_1_B,   // $C8
    SET_1_C,   // $C9
    SET_1_D,   // $CA
    SET_1_E,   // $CB
    SET_1_H,   // $CC
    SET_1_L,   // $CD
    SET_1_mHL, // $CE
    SET_1_A,   // $CF
    SET_2_B,   // $D0
    SET_2_C,   // $D1
    SET_2_D,   // $D2
    SET_2_E,   // $D3
    SET_2_H,   // $D4
    SET_2_L,   // $D5
    SET_2_mHL, // $D6
    SET_2_A,   // $D7
    SET_3_B,   // $D8
    SET_3_C,   // $D9
    SET_3_D,   // $DA
    SET_3_E,   // $DB
    SET_3_H,   // $DC
    SET_3_L,   // $DD
    SET_3_mHL, // $DE
    SET_3_A,   // $DF
    SET_4_B,   // $E0
    SET_4_C,   // $E1
    SET_4_D,   // $E2
    SET_4_E,   // $E3
    SET_4_H,   // $E4
    SET_4_L,   // $E5
    SET_4_mHL, // $E6
    SET_4_A,   // $E7
    SET_5_B,   // $E8
    SET_5_C,   // $E9
    SET_5_D,   // $EA
    SET_5_E,   // $EB
    SET_5_H,   // $EC
    SET_5_L,   // $ED
    SET_5_mHL, // $EE
    SET_5_A,   // $EF
    SET_6_B,   // $F0
    SET_6_C,   // $F1
    SET_6_D,   // $F2
    SET_6_E,   // $F3
    SET_6_H,   // $F4
    SET_6_L,   // $F5
    SET_6_mHL, // $F6
    SET_6_A,   // $F7
    SET_7_B,   // $F8
    SET_7_C,   // $F9
    SET_7_D,   // $FA
    SET_7_E,   // $FB
    SET_7_H,   // $FC
    SET_7_L,   // $FD
    SET_7_mHL, // $FE
    SET_7_A,   // $FF
];
